fabric8-analytics/fabric8-analytics-common

README.md

This is very simple change that (I suppose) was not spot during product rename because the original word was misspelled ;)

Fix wrong product name

---

integration-tests/features/steps/common.py

A nitpick-like change to make PEP8 checkers happier with this module used by tests.

Fix PEP8 128 error message

---

integration-tests/features/environment.py

This is another minor and nitpick-like fix for PEP8 warnings 128, 261, and 302.

Fix PEP8 warnings #128, 261, and 302

---

integration-tests/features/environment.py

Simple refactoring + change default endpoint to just /api/v1. The check if analysis (now stack-analysis) endpoint works should be part of integration tests itself, not part of setup ;)

Use the constant to specify API endpoint

---

integration-tests/features/environment.py

As we are starting to make tests for various services, let's refactor theirs port numbers.

Use constant for services ports (to be used by tests lately)

---

integration-tests/features/environment.py
integration-tests/features/steps/common.py

To test jobs API we'd need to have jobs API URL in test context. Additionally small refactoring has been performed.

Jobs api url in context

---

integration-tests/features/jobs_api.feature
integration-tests/features/steps/common.py

Another simple test case - check the initial number of jobs in the system. The next step would be to insert new job, check if it is in the system etc. (according to existing API scheme)

Initial number of jobs

---

integration-tests/features/smoketest.feature

Now the /api/v1 entrypoint is implemented for the jobs service, so we can check it. Here's the 1st step - smoketest ;)

New entrypoint to check in smoke test

---

integration-tests/features/jobs_api.feature

Another simple test that checks that it is not possible to delete job that does not exist.

Check that nonexistent job can't be deleted

---

integration-tests/features/steps/common.py

We need to check what happens if the HTTP PUT call to change the service state is called w/o the new state.

Step to reset job status service

---

integration-tests/features/steps/common.py

This is the 1st attempt to document all test steps.

Documentation for test steps, 1st attempt

---

integration-tests/features/steps/common.py

This step is for debug API so we will use it, but not as a part of an official integration test.

API call to get analyses report for selected ecosystem

---

integration-tests/features/jobs_api.feature

Simple check to make sure that HTTP DELETE API call checks for job ID existence

Check that job without ID can not be deleted

---

integration-tests/features/environment.py

This is quick & dirty test if server API and jobs API are running. It should fix the issue #82

Fixed issue #82

---

integration-tests/features/environment.py
integration-tests/features/steps/common.py

I'd like to create some tests for jobs debug API, so first we would need to be sure the API is running AND the DB is prepared as well (please see https://github.com/fabric8-analytics/fabric8-analytics-jobs/issues/87 why this step is needed here).

Jobs debug api readiness

---

integration-tests/features/steps/common.py

* ATM only 'start' and 'finish' states could be used, so make strict check
* the endpoint is component-analyses
* make this part PEP8-compatible (minor)

Make sure that only known states are used + use new endpoint + make PEP8-compatible

---

integration-tests/features/environment.py
integration-tests/features/steps/common.py

It is needed as component search service is started lately (and we can still run most of tests in the meantime ;)

Implemented prerequisite 'Component search service is running'

---

integration-tests/features/steps/common.py

The API response is a bit different now, so this is the proposed change.
Also json.loads() on 328 is needed ATM because of https://github.com/fabric8-analytics/fabric8-analytics-server/issues/64

Change caused by API updates

---

integration-tests/features/steps/common.py

Another change that is needed due to improvements on the API side:
* the stack-analyses now has new version stack-analyses-2, let's use the first one as default
* it supports Pythons's requirements.txt project specifications

Stack analysis now needs to be checked for 'version2' as well

---

integration-tests/features/steps/common.py

Usage if .feature files:
```
Then I should find the value requirements.txt under the path result/0/manifest_name in the JSON response
```

New check: find value under path

---

docker-compose.yml

it's used in [entrypoint.sh](https://github.com/fabric8-analytics/fabric8-analytics-data-model/blob/master/scripts/entrypoint.sh)
fixes:
`data-model-importer_1 | gunicorn: error: argument -w/--workers: invalid int value: 'rest_api:app'`

[docker-compose.yml] define NUMBER_WORKER_PROCESS

---

integration-tests/features/steps/common.py

Some responses contains the 'T' separator in the timestamp, so we should be able to accept such timestamps.

Better check for timestamp - the 'T' separator

---

integration-tests/features/steps/common.py

Support for following case + very minor refactoring:
```
When I wait for stack analysis version 2 to finish
Then I should get 200 status code
Then I should find analyzed dependency named click with version 6.7 in the stack analysis
Then I should receive JSON response with the correct timestamp in attribute started_at
Then I should receive JSON response with the correct timestamp in attribute finished_at
Then I should find proper timestamp under the path result/0/_audit/started_at
Then I should find proper timestamp under the path result/0/_audit/ended_at
```

Check timestamp under the given path in the JSON response

---

integration-tests/features/steps/common.py

It seems we will need to test analyzed dependencies very frequently so I think it would be good to be able to define following checks:
```
Then I should find analyzed dependency named click with version 6.7 in the stack analysis
```

Check analyzed dependency

---

integration-tests/requirements.txt

Just and update of requirements.txt used by integration tests. I've also added note howto install pip-compile (it is not obvious for Python apprentices ;)

Updated requirements.txt + added note howto install pip-compile

---

integration-tests/features/steps/common.py

We need to test the authentication module as well, so we can accept HTTP 401 and check it later.

Start analysis http codes

---

docker-compose.integration-tests.yml
integration-tests/features/environment.py

The settings for integration tests might be different that settings that devels want to use. This particular change make sure that authentication module is not disabled during testing.

Integration tests specific settings

---

integration-tests/features/steps/common.py

Component search REST API endpoint can be call with authorization token (production + CI) or without it (devels).

Search for component can be call with or without authorization token

---

integration-tests/features/stack_analyses_v2.feature
integration-tests/features/steps/common.py

Special step that is needed to get the stack analysis outlier probability threshold. That value is to be used in ongoing stack analysis v2 tests, and we don't want to use fixed magic constant in such tests.

Download stack analysis threshold value

---

integration-tests/features/environment.py

Check for the component service availability should check the 401 code as well when auth is enabled.

Allow waiting for the service with authorization

---

integration-tests/features/steps/common.py

Use the provided authorization token on openshift instance. Please note that it's been checked only locally.

Use authorization token from the env. variable if provided

---

integration-tests/features/components.feature

Should allow the tests to be run on stage.

Don't explicitly ask for the generated 'local' authentication token, use provided one (if it exist)

---

integration-tests/feature_list.txt

Integration tests have failed because of some failed scenarios in the integration test. Hence, commenting that as a temporary measure.

Comment out stack analyses feature of int test

---

integration-tests/features/environment.py

Just two checks to inform users/testers about the test environment (the logic should behave the same)

Info users about test environment

---

docker-compose.yml

Follow-up of https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/183

[docker-compose.yml] define SCANCODE_PROCESSES to speed up license scans

---

integration-tests/features/steps/common.py

It took ages to wait for stack analysis results ;) so it is quite difficult to check that all test steps are correct. This step allow us to simply mock JSON file as API result (another option would be to use requests-mock package, but it seems not to be necessary ATM)

Ability to mock API results into the tests

---

integration-tests/features/steps/common.py

On stage it does not make much sense to check for fixed 'magic' number of jobs, but use relative number N+x instead ;)
(I'll make new PR with changes in tests later)

Checking number of jobs

---

integration-tests/features/steps/common.py

The 1st step to resolve #208 - if there's environment variable with the job API token, use it.
Usage:
```
Scenario: Check initial number of jobs
Given System is running
When I acquire job API authorization token
Then I should get the proper job API authorization token
When I access jobs API /api/v1/jobs with authorization token
Then I should get 200 status code
Then I should see 4 jobs
```

Auth method for jobs api

---

integration-tests/features/jobs_api.feature
integration-tests/features/steps/common.py

Couple of smaller changes:
* optional usage of unique job IDs (a must on stage/production)
* use auth. token for delete a job
* use auth. token to cleanup jobs
* use auth. token to change the service state
* use auth. token to retrieve service state
* all tests should use proper auth. token
* other fixes to hopefully make CI tester happy :) [it actually does 🥇 ]

Unique job ids + use authorization + test fixes

---

ui-tests/test.py

That's a bit strange, but the click in the 'Ok' button is needed in the last step so the repo is shown on the Space page.

The last step of new Space wizard

---

integration-tests/features/environment.py

Sometimes (but not very often) the tests failed on the stage due to stack analysis timeout. Let's increase the default timeout value to be on the safe side.

Increase timeout for the stack and component analysis

---

integration-tests/cico_run_tests.sh
integration-tests/features/user_feedback.feature

There is still no token in CentOS CI...

Disable tests which require auth in CentOS CI for now - no token

---

perf-tests/src/coreapi.py

In order to display measured durations we need to be able to read the results

Inserted missing return (quick, minor)

---

docker-compose.yml

Add an environment variable for github token in Jobs as it is required to gh_most_stared api in local run.

add github token for gh_most_stared api

---

docker-compose.yml

Providing S3 credentials in local setup means that database adapters are trying to connect to remote S3 instead of the local one.

Do not provide S3 credentials on local setup

---

postgres-docker/README.md
postgres-docker/common.sh
postgres-docker/multiple_dbs.patch
postgres-docker/update_common.sh

In recent update upstream of Postgres image, which we use introduced changes which can break our setup.
This PR extracts our changes in `common.sh` and adds scripts which download the latest version of `common.sh` and applies this changes.
I don't want to run update script in `Dockerfile`, because there is no patch binary available and default user is switched to Postgres.
If anybody thinks that it will be more transparent to move script inside `Dockerfile`, I will gladly do it.

[Postgres] Update to latest version of common

---

integration-tests/features/steps/common.py

These changes might be enough ATM to check analyses of libraries.io and for keywords tagging. I'm not sure about the word weight, now the check is weight > 0.0 (should be >= 0.0?)

More s3 data checks

---

perf-tests/src/api.py

Just a quick fix not to fail when core API does not return error message.

Don't fail when core API returns HTTP 500 w/o any payload

---

integration-tests/features/stack_analyses_v2_minimal.feature

We should not rely on e2e tests asserting count of outliers detected from recommendation service. Reason - Each time when a model is retrained with new datasets, this outlier, alternate and companion changes in terms of recommendations.

E2e test change - remove outlier count validation tests

---

perf-tests/src/perf-tests.py

Default argument values are evaluated only once at function
definition time, which means that modifying the default value
of the argument will affect all subsequent calls of the function.

Don't use mutable as default value of argument

---

openshift/secrets-template.yaml

This commit adds 'three scale api access key'
and 'three scale api account' id as secret variables
in openshift template.

Adding 3scale credentials

---

perf-tests/data/junit.xml
perf-tests/data/springboot.xml
perf-tests/data/vertx_3_4_1.xml
perf-tests/data/vertx_3_4_2.xml
perf-tests/src/cliargs.py
perf-tests/src/coreapi.py
perf-tests/src/perf-tests.py

Support for the following call:
```
./runtest.sh -S --manifest=vertx_3_4_2.xml
```
ie. it is possible to specify manifest file that will be sent for the stack analysis.

Configurable stack analysis manifest

---

integration-tests/features/gremlin.feature
integration-tests/features/src/graph_db_query.py
integration-tests/features/steps/gremlin.py

The new tests are not much useful, but we'd need to have the timestamp check for the following tests that will wait for the analysis (started from jobs API) to finish.

Timestamp checks

---

openshift/deploy.sh

In some cases (in container) the 'oc login' shows only `<default>` project
even the OC_PROJECT exists.

Use 'oc get project' instead of grep

---

integration-tests/features/three_scale.feature

This change is in accordance to the change of status code in 3scale-connect-api.
reference:-
https://github.com/fabric8-analytics/f8a-3scale-connect-api/pull/22

Change in status code for a 3scale test.

---

dashboard/src/html_generator.py
dashboard/src/results.py
dashboard/template/dashboard.html
dashboard/template/repo_details.html

Display timestamp at the end of all generated pages, like:
and
https://fabric8-analytics.github.io/dashboard/repository_fabric8-analytics-common.html

Timestamp on dashboard

---

openshift/README.md
openshift/cleanup.sh
openshift/deploy.sh
openshift/helpers.sh
openshift/purge_AWS_resources.py

Please review with care as this is potentially destroying functionality.
1.  Previously if we found already existing RDS database, we were recreating it.
With this change we by default purge also previously allocated (`$DEPLOYMENT_PREFIX` prefixed) SQS queues, S3 buckets, DynamoDB tables.
The purging can be avoided by using `--keep-resources` argument.
The question is whether we by default really want to purge all those AWS resources, or whether we by default want to keep some of them (like S3 buckets?) ?
2. The new `hack/purge_AWS_resources.py` has also a `-t/--tag` option, which when specified, causes the script to delete all AWS resources [tagged](https://github.com/openshiftio/openshift.io/issues/1081) with this tag.
Fixes https://github.com/openshiftio/openshift.io/issues/1330

[openshift/deploy.sh] delete previously allocated AWS resources

---

dashboard/config.ini
dashboard/src/dashboard.py
dashboard/src/results.py
dashboard/template/dashboard.html

Original issue: https://github.com/openshiftio/openshift.io/issues/1794
Please look at: https://fabric8-analytics.github.io/dashboard/dashboard.html where the new column is displayed (top right corner)

Issue 1794: The QA Dashboard should display current status of the e2e tests for the production environment

---

dashboard/src/ci_jobs.py
dashboard/src/dashboard.py
dashboard/src/results.py
dashboard/template/dashboard.html

Ability to display code coverage results on the dashboard:
Please note that 'bar meters' are not displayed for repositories w/o any unit tests.

Display code coverage report

---

integration-tests/features/environment.py
integration-tests/features/server_api.feature

in https://github.com/fabric8-analytics/fabric8-analytics-worker/commit/bd244453ce6f47c47927e3ecbfad12fc4e1c14b8
see failing https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/812/consoleFull

Blackduck analysis was removed

---

integration-tests/feature_list.txt
integration-tests/features/stack_analyses_pypi_ecosystem.feature

@miteshvp it fix the issue caused by data migration. Unfortunately there are two other issues that cause the e2e to fail, so right now we are blocked by them.
Another two test features has been commented out, it's based on our agreement on cabal not to test things not used on production.

Stack analysis PyPi ecosystem tests fix + fix for other tests

---

README.adoc
check-docstyle.sh
detect-common-errors.sh
detect-dead-code.sh
directories.txt
run-linter.sh

This PR implements the first task in:
https://jira.coreos.com/browse/APPAI-516
Make all QA-related tools more effective and easier to use by developers
1. All QA-related scripts needs to be made unified by using external list of directories to check
2. All QA-related scripts needs to be moved into separate subdirectory
3.QA Dashboard should be updated to use the new scripts (as #1)
JIRA issue for the 1st task:
https://jira.coreos.com/browse/APPAI-481
Currently, several QA-related scripts have the 'source-directories' included in the script body. It would be nice to use separate and central configuration file for this.

QA script use directories.txt

---

dashboard/ci_jobs.ini
dashboard/config.ini

Fabric8-analytics-scaler repository has been added to the QA Dashboard
Fixes #761

Add the fabric8-analytics-scaler repository to the QA Dashboard

---

integration-tests/features/components.feature
integration-tests/features/server_api.feature
integration-tests/features/user_intent.feature

Remove all the feature tests from hourly prod E2E tests that are not available via IDE extensions.

remove endpoints not accessed by IDE extension from the hourly prod E2E

---

integration-tests/features/stack_analysis_npm_direct_and_transitive.feature
integration-tests/runtest.sh

I have Increased the duration from 40 to 120 secs for npm 150 direct and 1170 transitive dependencies
increase the stack analysis timeout to 120 sec
- [- ] Bug fix (non-breaking change which fixes an issue)

Increase the stack analysis timeout for npm direct and transitive deps to 120 secs

---

integration-tests/features/component_analysis.feature
integration-tests/features/component_analysis_smoke_tests.feature
integration-tests/features/component_analysis_smoke_tests_100_maven_components.feature
integration-tests/features/component_analysis_smoke_tests_100_npm_components.feature
integration-tests/features/component_analysis_smoke_tests_100_pypi_components.feature
integration-tests/features/component_analysis_v2.feature
integration-tests/features/components.feature
integration-tests/features/steps/component_analysis_v2.py
integration-tests/features/steps/three_scale_preview.py
integration-tests/requirements.txt

Migrated v1 component analysis tests to 3scale auth and fixed CA v2 429 code with future requests 

Migrated v1 component analysis tests to use 3scale auth 

---

integration-tests/feature_list.txt

disabling stack analysis smoke feature so that e2e doesn't block license and worker deployments

disabling smoke tests to clear out 408 failures 

---

integration-tests/features/steps/component_analysis_v2_batchcall.py

added trailing slash in CA post route according to lsp

fix: add trailing slash in CA post route 

---

integration-tests/e2e.sh

Disabling e2e until platform Maintenance is completed

fix: Disable e2e for postgres upgrade
