fabric8-analytics/fabric8-analytics-common

Jenkinsfile

And annotate underscore instead

[Jenkinsfile] Remove unused variable

---

docker-compose.yml

Needed by https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/2

[docker-compose] jobs need to use S3

---

docker-compose.devel.yml

Needed by https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/11

Rename bayesian_jobs/ to f8a_jobs/

---

integration-tests/README.md

Link to detailed steps how to setup Docker so users/devels don't have to google it ;)

Provide link to docker setup

---

docs/developing_running.md

"Fix" for the https://github.com/fabric8-analytics/gremlin-docker/issues/8

Note about some error that can be displayed in the log

---

Jenkinsfile
docker-compose.devel.yml
docker-compose.yml
docs/developing_running.md
integration-tests/README.md
integration-tests/feature_list.txt
integration-tests/features/smoketest.feature

Let's start working on more integration  tests. This is the very first and very simple version for smoke test. At least it allow us not to start just the fake 'disabled' test.

1st version of smoke test

---

integration-tests/feature_list.txt
integration-tests/features/server_api.feature
integration-tests/features/steps/common.py

1st set of server API tests (now just tests that don't change the internal state of the app).

Server api tests

---

integration-tests/features/smoketest.feature

Check for several API endpoints (ATM I just check the HTTP code, not the returned content)

Smoketests for several API endpoints

---

integration-tests/features/steps/common.py

I'd need this function for new tests I'm working on, so pls review this simple change. TY in advance.

Test step to check if deserialized JSON contains given value

---

integration-tests/feature_list.txt
integration-tests/features/jobs_api.feature

1st set with very basic checks

Jobs API tests

---

integration-tests/data/job1.json
integration-tests/features/environment.py
integration-tests/features/jobs_api.feature
integration-tests/features/steps/common.py

This test (in its simplest) form needs some changes in common.py and environment.py modules.

Test if new job can be created via API call

---

integration-tests/features/jobs_api.feature

New test case - check if multiple jobs can be registered via API

Test if multiple jobs can be registered

---

integration-tests/features/steps/common.py

Minor refactoring & adding test step that allow us to create new job with given ID (that could be checked later)

New test step: create new job with given ID

---

integration-tests/features/jobs_api.feature
integration-tests/features/steps/common.py

The last thing for this week ;) Simple test that the registered job is mentioned in the job list.

Test if job is registered

---

integration-tests/features/steps/common.py

Another new simple test step that would be needed to develop new API tests.

Test that job is not yet in the system

---

integration-tests/features/jobs_api.feature

Test if new jobs don't replace the existing ones

Test if jobs are not replaced

---

integration-tests/README.md
integration-tests/common.html
integration-tests/generate_doc.sh

This is quite ugly version of documentation generated for the common.py module, but giving we don't have anything else ATM I'd like to use this document generated by pydoc.

Generate documentation - 1st version

---

integration-tests/features/steps/common.py

This is a new test step to delete job with given ID  via API call.

Test step to delete job via API call

---

integration-tests/features/jobs_api.feature

With the fixes done today in the job API, the new test should pass.

Test that jobs can be deleted

---

integration-tests/features/steps/common.py

New test step that allow us to change job status (and see the HTTP code etc.)

Test step change job status

---

integration-tests/MAINTAINERS

I want to be famous ;) for contribution to integration tests.

Added myself into list of maintainers

---

integration-tests/features/jobs_api.feature

* Check that job status can be changed
* Check wrong status behaviour
* Check setting status for wrong job behaviour

Three new scenarios for API call to change job status

---

integration-tests/features/steps/common.py

New test step to be used for checking job service state API

Service state change test step

---

integration-tests/features/jobs_api.feature

Check if it is possible to manipulate with service state.

Check job service state manipulation

---

integration-tests/features/steps/common.py

Another test step we'd need to have for integration tests.

API call to clean up failed jobs

---

integration-tests/features/jobs_api.feature

* Check if improper job service state is detected properly
* Check if new job service state is checked
* Check the API call to clean all failed jobs

Three new test scenarios

---

integration-tests/features/steps/common.py

Actually this is prerequisite for https://github.com/fabric8-analytics/fabric8-analytics-common/pull/73
I forgot to do this PR first, sorry!

Test step to try to delete job without ID

---

integration-tests/features/steps/common.py

Fix for https://github.com/fabric8-analytics/fabric8-analytics-common/issues/76 found by @fridex (TY!)

Don't shadow id() function by parameter names or local function names

---

integration-tests/features/jobs_api.feature

Reverts fabric8-analytics/fabric8-analytics-common#79

Revert "Disable all jobs tests for now"

---

integration-tests/features/jobs_api.feature

Reverts fabric8-analytics/fabric8-analytics-common#80

Revert "Revert "Disable all jobs tests for now""

---

integration-tests/features/jobs_api.feature

Reverts fabric8-analytics/fabric8-analytics-common#81

Revert "Revert "Revert "Disable all jobs tests for now"""

---

integration-tests/features/smoketest.feature

Reverts fabric8-analytics/fabric8-analytics-common#85

Revert "Disable Jobs smoketests due to slow Jenkins slaves"

---

integration-tests/features/jobs_api.feature

Not super-advanced test steps, but let's make sure that all combinations of service state could be set.

Job API state test

---

integration-tests/features/steps/common.py

Simple addition, test step to search for given component using component-search endpoint.

Test step: search for component

---

integration-tests/features/steps/common.py

Due to changes in component analysis API, the steps to start the analysis and to wait for finish need to be rewritten completely.

Component analysis steps for current API

---

integration-tests/features/steps/common.py

Another simple test step we'd need to implement for new ongoing tests.

New test stept to read component analysis

---

integration-tests/features/steps/common.py

For the new tests we need to check if the object returned from API (via JSON) contains a given attribute/value stored in nested structure of objects and lists. This helper function allow us to develop these tests quite easily.
An example (component analysis result), the path for the given attribute might look like:
"data/0/package/ecosystem/0"

Function to get attribute using path

---

integration-tests/data/requirements.txt
integration-tests/features/stack_analyses_v2.feature
integration-tests/features/steps/common.py

The test uses requirements.txt I got from asrisail, ie. file with known stack analysis output.

Basic tests for stack analyses v2

---

integration-tests/features/steps/common.py

New check 'I should find the attribute request_id equals to id returned by stack analysis request' needed by new tests being prepared (and not sent to review before this PR)

Check stack analysis

---

integration-tests/requirements.txt

Reverts fabric8-analytics/fabric8-analytics-common#130

Revert "Updated requirements.txt + added note howto install pip-compile"

---

integration-tests/features/steps/common.py

Fix for various PEP257 violations.

PEP257-like comments in steps.py

---

integration-tests/features/steps/common.py

Ugh so many changes are needed to be able to test authorization. This might be the last one ;)

Allow waiting for stack analysis with auth token

---

openshift/config-template.yaml

And set default deployment prefix to "dev" (was "DEV").

[openshift] Add Keycloak URL to config map

---

integration-tests/features/steps/common.py

Update needed by change in stack analysis v2 API mentioned here:
https://github.com/openshiftio/openshift.io/issues/378

Reflect changes in stack analysis v2 API

---

integration-tests/features/steps/common.py

Support for stack analysis v2 and component analysis REST API that require auth tokens

New test step to use auth token to access URL

---

integration-tests/features/stack_analyses_v2.feature

Better version of stack analyses v2 tests that surpasses #122 and #110

Stack analyses v2 tests with authorization

---

integration-tests/data/pom-minimal.xml
integration-tests/data/pom.xml

Just two example pom.xml files we are going to use in tests.

pom.xmls to be used by stack analysis tests

---

integration-tests/features/steps/common.py

Special test step for checking outlier probability in the generated stack analysis v2.

Test step to check outlier probability

---

integration-tests/features/stack_analyses_v2.feature

Updated to match changes made on CI

Use provided authorization key in stack-v2 tests

---

integration-tests/feature_list.txt

Please merge this requests whenever you need to run the stack analysis v2 integration tests against stage.

Enable stack analysis integration tests

---

integration-tests/features/steps/common.py

New test step to be used for stack-analysis-v2 tests (ATM we don't have a data to check).

Check licenses

---

integration-tests/features/components.feature
integration-tests/features/stack_analyses_v2.feature
integration-tests/features/stack_analyses_v2_minimal.feature

@fridex you asked for this feature ;)

Test tags authorization token

---

integration-tests/features/steps/common.py

Hi @fridex, I made an ugly mistake there and now it prevents me to use this test step in our integration tests :/

Fixed wrong parameter name

---

integration-tests/data/mock_stack_analysis_v2_junit.json
integration-tests/data/mock_stack_analysis_v2_springboot.json
integration-tests/data/mock_stack_analysis_v2_vertx.json
integration-tests/feature_list.txt
integration-tests/features/selfcheck.feature

A simple (ATM) selfcheck of several test steps implementation + mocked JSON files fetched from the system with live data.

Integration tests selfcheck

---

integration-tests/features/stack_analyses_v2.feature

Basic tests for vertx.xml and springboot.xml as well as for pom.xml with just one dependency (form of smoketest).

Maven tests version 1

---

integration-tests/features/steps/common.py

More refactoring for the job ID stuff + better checks for the response

Stack analysis id and request id checks

---

integration-tests/features/stack_analyses_v2.feature

Check if the job ID is the same as request_id returned by the stack analysis report + check if both IDs has the proper content (hexa string etc. etc.)

Checks for the job ID + request_id returned in the stack analysis

---

integration-tests/feature_list.txt
integration-tests/features/stack_analyses_v2_minimal.feature
integration-tests/features/steps/common.py

@tisnik closing https://github.com/fabric8-analytics/fabric8-analytics-common/pull/189 as I messed that up during merge conflict resolution.

Minimal Stack Analyses V2 tests

---

integration-tests/features/environment.py

Just a slight refactoring, enhancement + fixed some PEP8 warnings as well.

Check if the JOB_API_TOKEN is set up properly

---

.gitignore
integration-tests/features/environment.py
run-linter.sh

ATM only the integration-tests directory is checked, just to make sure everything's ok.
Also - Jenkinsfile is not updated yet

Linter 1st version

---

ui-tests/test.py

First two steps needed to test stack analysis:
* front page
* login

Ui tests front page and login

---

docker-compose.firehose-fetcher.yml

This is tied with https://github.com/fabric8-analytics/fabric8-analytics-firehose-fetcher/pull/1

Added firehose-fetcher service

---

integration-tests/features/jobs_api.feature
integration-tests/features/steps/common.py

Dirty tests for the logout endpoint

Jobs logout endpoint

---

ui-tests/test.py

ATM this test creates new Space with unique name.
Hmm I'm thinking about using Behave for UI tests as well, WDYT?

UI test create new Space

---

Jenkinsfile
run-linter.sh

ATM the linter is run against the fabric8-analytics-common repo content. I need to figure out how to run it against other source repositories as well.

Run linter on ci

---

integration-tests/features/stack_analyses_v2_minimal.feature

Disable the test temporarily

---

integration-tests/features/steps/common.py

This should fix the HTTP 500 code issue.

Fix stack analysis v2 POST call

---

integration-tests/data/mock_stack_analysis_v2_junit.json
integration-tests/data/mock_stack_analysis_v2_requirements.json
integration-tests/data/mock_stack_analysis_v2_springboot.json
integration-tests/data/mock_stack_analysis_v2_vertx.json
integration-tests/features/selfcheck.feature
integration-tests/features/steps/common.py

Looks like the node 'recommendation**S**' has been renamed, so this is the 1st thing that needs to be updated in integration tests. I've also updated other test steps that access the recommendation node.

Fixed NPE + renamed node to test

---

integration-tests/features/jobs_debug_api.feature
integration-tests/features/smoketest.feature
integration-tests/features/steps/common.py

Tests for the /debug/analyses-report REST API endpoint + changes needed to be made in the common.py module.

Debug analyses report comprehensive tests

---

integration-tests/features/jobs_debug_api.feature

This is addition to already merged tests - checks if bad or improper input is detected and rejected with HTTP code 400.

Checks for the bad/improper input

---

integration-tests/features/components.feature
integration-tests/features/steps/common.py

Update - component analysis API call could use auth. token for testing remote service

Component analysis api call with token

---

integration-tests/features/environment.py

Basic methods for the 'context' object needed to access S3 database from tests.

Access to s3 for tests

---

integration-tests/features/steps/common.py

Following changes are needed for checking component metadata and analysis in the AWS S3 database.

Search for components in AWS S3

---

integration-tests/features/component_search.feature
integration-tests/features/components_in_s3.feature
integration-tests/features/environment.py
integration-tests/features/steps/common.py

Checks for component search results + basic checks for component metadata stored in the S3 database.

Search in s3

---

perf-tests/src/api.py
perf-tests/src/benchmarks.py
perf-tests/src/coreapi.py
perf-tests/src/graph.py
perf-tests/src/jobsapi.py

(please note that stack analysis can't be run ATM because it is broken on stage)

Performance tests 2nd version

---

perf-tests/data/job_pypi_clojure_py.json
perf-tests/requirements.in
perf-tests/requirements.txt
perf-tests/src/jobsapi.py
perf-tests/src/s3interface.py

We need these changes to be able to run perftests for flow scheduling.

Performance tests flow scheduling

---

perf-tests/src/graph.py

Usage:
```
durations1 = {
"overall": Duration("2017-09-12T10:17:39.335428", "2017-09-12T10:30:45.478105"),
"security_issues": Duration("2017-09-12T10:26:32.123411", "2017-09-12T10:27:02.913608"),
"github_details": Duration("2017-05-19T02:44:26.477892", "2017-05-19T02:44:26.556793"),
"source_licenses": Duration("2017-09-12T10:25:41.169322", "2017-09-12T10:26:21.857600"),
"metadata": Duration("2017-09-12T10:27:14.276409", "2017-09-12T10:27:15.228278"),
"keywords_tagging": Duration("2017-09-12T10:28:21.858944", "2017-09-12T10:28:41.847464"),
"dependency_snapshot": Duration("2017-09-12T10:28:00.584849", "2017-09-12T10:28:00.591810"),
"digests": Duration("2017-09-12T10:25:40.634570", "2017-09-12T10:25:40.923991"),
"code_metrics": Duration("2017-05-19T02:44:08.432101", …
```

Function to create graph with detailed time data about component analyses flow

---

perf-tests/src/jobsapi.py
perf-tests/src/perf-tests.py

* show thread ID during waiting for component analysis to finish
* possibility to explicitly specify ecosystem+component+version to be analyzed
* other minor improvements (indentation etc.)

Show thread

---

integration-tests/features/src/s3interface.py

ATM the whole S3 interface is part of environment module, which is quite dirty. Let's use separate module with all required logic.

S3 interface to be used in integration tests

---

perf-tests/src/graph.py
perf-tests/src/measurements.py

Update to create following graphs: https://raw.githubusercontent.com/fabric8-analytics/fabric8-analytics.github.io/master/perf-tests/jobs_api/flow_analysis/pypi_clojure_py.png

Component and package perf test results

---

integration-tests/features/environment.py
integration-tests/features/src/s3interface.py
integration-tests/features/steps/common.py

Integration of the new s3interface module introduced by #286.

Integration tests use new s3 module

---

run-linter.sh

The same issue you found in other repo :/

Remove leftover from debugging the script

---

integration-tests/feature_list.txt
integration-tests/features/stack_analyses_v2_minimal.feature
integration-tests/features/steps/common.py

1. Added an unimplemented scenario
2. Uncommented stack_analyses_v2_minimal.feature

Added an unimplemented test scenario

---

docker-compose.devel.yml
docs/developing_running.md
setup.sh

Since https://github.com/fabric8-analytics/fabric8-analytics-worker/commit/1c619004e8fce06d208476a50df068ddd088f3f7

Worker doesn't use secrets.yaml anymore

---

integration-tests/features/selfcheck.feature
integration-tests/features/steps/common.py

1st part, not to disturb you by a big changeset

Check component data in s3

---

integration-tests/features/selfcheck.feature
integration-tests/features/steps/common.py

2nd part of checking of component data stored in the S3

Check component data in s3 second part

---

integration-tests/features/src/attribute_checks.py
integration-tests/features/steps/common.py

This is the 1st part of https://github.com/openshiftio/openshift.io/issues/1076

Refactoring attribute checks functions

---

integration-tests/features/src/attribute_checks.py

Let's this module be the first that passes Pydocstyle check! :)

Fix all pydocstyle warnings

---

integration-tests/features/src/s3interface.py
integration-tests/features/steps/authorization.py
integration-tests/features/steps/common.py
integration-tests/features/steps/jobs_api.py
integration-tests/features/steps/s3_component_analysis.py
integration-tests/features/steps/s3_interface.py
integration-tests/features/steps/s3_package_analysis.py
integration-tests/features/steps/server_api.py
integration-tests/features/steps/stack_analysis.py

This is the last part that needs to be done to close https://github.com/openshiftio/openshift.io/issues/1076

Tests refactoring final part

---

dashboard/src/dashboard.py
dashboard/src/results.py
dashboard/template/dashboard.html

New version of dashboard: https://fabric8-analytics.github.io/dashboard/dashboard.html
(the last PR for today, I promise :)

Code overall results and remarks

---

dashboard/src/dashboard.py
dashboard/src/html_generator.py
dashboard/template/dashboard.html
dashboard/template/repo_details.html

An example of actual output generated by this change:
https://fabric8-analytics.github.io/dashboard/repository_fabric8-analytics-stack-analysis.html

Dashboard code checks statistic

---

dashboard/src/dashboard.py
dashboard/template/dashboard.html
dashboard/template/repo_details.html

Just a minor improvement on the dashboard side

Display total line count

---

integration-tests/features/steps/stack_analysis.py

This needs to be pulled in before #334

New test step - I should find _dependency_ + minor fix

---

integration-tests/data/updated_stack_analysis_v2.json
integration-tests/features/selfcheck.feature
integration-tests/features/steps/stack_analysis.py

Here is the latest stack analyses response for the ready reference of the reviewer - https://gist.github.com/samuzzal-choudhury/7a21f8da317b1771c5973e9b9faf0d7a
The current error during the integration tests is -
```
Traceback (most recent call last):
File "/usr/lib/python3.4/site-packages/behave/model.py", line 1456, in run
match.run(runner.context)
File "/usr/lib/python3.4/site-packages/behave/model.py", line 1903, in run
self.func(context, *args, **kwargs)
File "/tests/features/steps/stack_analysis.py", line 318, in stack_analysis_check_companion_packages
analyzed_packages = get_analyzed_packages(json_data)
File "/tests/features/steps/stack_analysis.py", line 302, in get_analyzed_packages
return get_attribute_values(analyzed_packages, "package")
File …
```

Changes stack analyses scenario tests for new schema

---

integration-tests/data/clojure_py_core_data/0.2.4/security_issues.json
integration-tests/features/steps/s3_component_analysis.py

Required for https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/420

[integration-tests] Bump security_issues schema

---

integration-tests/features/environment.py
integration-tests/features/src/MockedResponse.py
integration-tests/features/src/attribute_checks.py
integration-tests/features/src/authorization_tokens.py
integration-tests/features/src/json_utils.py
integration-tests/features/src/parsing.py
integration-tests/features/src/s3interface.py
integration-tests/features/src/utils.py
integration-tests/hack/json2pom.py

1st part of #1224
- all Python sources in the integration-tests subdirectory should have proper docstrings

Update pydocs in integration tests

---

ui-tests/setup.cfg
ui-tests/test.py

2nd part of #1224
- documentation strings for UI tests: the whole module, class (just one ATM), and all public functions

Pydocstyle in ui tests

---

perf-tests/src/perf-tests.py

Sometimes we are asked to run selected benchmarks only. This is the first part of this approach that allow us to:
1) decide whether to run stack analysis and/or component analysis
2) enable parallel tests

Use basic CLI options to control, which tests to start

---

perf-tests/src/api.py
perf-tests/src/benchmarks.py
perf-tests/src/cliargs.py
perf-tests/src/componentgenerator.py
perf-tests/src/coreapi.py
perf-tests/src/duration.py
perf-tests/src/graph.py
perf-tests/src/jobsapi.py
perf-tests/src/measurements.py
perf-tests/src/perf-tests.py
perf-tests/src/s3interface.py

The last set of fixes needed by #1224

Fixed docstrings in all modules for perf. tests

---

dashboard/src/dashboard.py
dashboard/template/dashboard.html

Generated results can be seen here:

Progress bars in dashboard

---

perf-tests/src/coreapi.py

We need to wait for all worker to finish in the performance tests.

Wait for the full stack analysis results, including recommendations

---

perf-tests/src/benchmarks.py
perf-tests/src/coreapi.py
perf-tests/src/perf-tests.py

Code improvement needed to be able to retrieve job durations performed during stack analysis.

Stack analysis job durations

---

perf-tests/src/cliargs.py
perf-tests/src/coreapi.py
perf-tests/src/jobsapi.py
perf-tests/src/perf-tests.py

Ability to dump JSON responses returned from the API or read from the S3.

Json responses dump

---

setup.sh

Do not clone firehose-fetcher and stack-analysis

---

integration-tests/feature_list.txt
integration-tests/features/environment.py
integration-tests/features/steps/user_tag.py
integration-tests/features/user_tag.feature

Integration tests for crowdsourcing API endpoints:
- get master tag list for given ecosystem
- get next component to be tagged for given ecosystem
- set tags to component

Integration tests for crowdsourcing API

---

integration-tests/features/stack_analyses_v2_minimal.feature
integration-tests/features/steps/stack_analysis.py

PR to address https://github.com/openshiftio/openshift.io/issues/1458

Added tests to verify component-topics mapping for stack analysis

---

integration-tests/features/gremlin.feature

The last PR for today, I promise :)

Test for the Pypi ecosystem packages in the graph database

---

openshift/deploy.sh

Add openshift template for stack report UI
Change shebang to fit mac users

Add stack report UI template

---

openshift/secrets-template.yaml

Signed-off-by: invinciblejai <mailjai.vardhan@gmail.com>

updates secrets for 3scale apicast gateway

---

openshift/README.md
openshift/deploy.sh
openshift/env-template.sh
openshift/run-2e2-test.sh

Updated documentation
Added script to run e2e tests
Changed script formatting

E2E test and documentation

---

openshift/deploy.sh

[aws rds add-tags-to-resource doc](http://docs.aws.amazon.com/cli/latest/reference/rds/add-tags-to-resource.html)
Related to https://github.com/openshiftio/openshift.io/issues/1081

Add tag to RDS instance

---

docker-compose.yml

Related to https://github.com/openshiftio/openshift.io/issues/1270

crowd source tags cleaning

---

openshift/deploy.sh

Tested this time ;-) (on Fedora and in container)

Run deploy.sh through www.shellcheck.net

---

integration-tests/features/components.feature
integration-tests/features/server_api.feature
integration-tests/features/stack_analyses_v2_minimal.feature

Another set of tests that we want to run on prod.

Tests to be run on production

---

openshift/README.md

That section didn't tell me how can I use my testing image from a PR.
I don't know if what I changed it to is the correct work-flow, but it works for me.

[openshift/README.md] (hopefully) improve 'Deploy changes to dev' section

---

dashboard/clone_or_pull_all_repos.sh

Script that makes a local clone of all relevant Fabric8 repositories
The content of repositories are to be used to generate dashboard

Script to clone all relevant Fabric8 repositories

---

openshift/config-template.yaml
openshift/deploy.sh

I need this for https://github.com/fabric8-analytics/gremlin-docker/pull/22 (where I add a script, which runs `aws` cli, which needs a `AWS_DEFAULT_REGION` to be set).

Openshift deploy env aws default region

---

dashboard/src/cliargs.py
dashboard/src/dashboard.py
dashboard/src/html_generator.py
dashboard/template/dashboard.html

Implementation of https://github.com/openshiftio/openshift.io/issues/1743

Provide cli options for the dashboard generator

---

docker-compose.yml

needed for https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/211

[docker-compose] jobs links gremlin-http

---

dashboard/src/ci_jobs.py
dashboard/src/dashboard.py
dashboard/src/results.py
dashboard/template/dashboard.html

The second part of https://github.com/openshiftio/openshift.io/issues/1739

Display status of the last build on dashboard

---

perf-tests/src/benchmarks.py
perf-tests/src/cliargs.py
perf-tests/src/gremlin_api.py
perf-tests/src/gremlin_package_generator.py
perf-tests/src/gremlin_query.py
perf-tests/src/perf-tests.py

This is the 1st part of https://github.com/openshiftio/openshift.io/issues/1528
(sequence perf tests ATM)

Graph db sequence perf test

---

perf-tests/src/benchmarks.py
perf-tests/src/perf-tests.py

The second (and the last) part of https://github.com/openshiftio/openshift.io/issues/1528

Graph db parallel perf test

---

integration-tests/data/clojure_py_package/github_details.json
integration-tests/features/components_in_s3.feature
integration-tests/features/src/attribute_checks.py
integration-tests/features/src/s3interface.py
integration-tests/features/steps/s3_component_analysis.py
integration-tests/features/steps/s3_package_analysis.py

I have the S3 credentials (at last!), so it is the right time to improve and fix some issues in S3 tests ;)

S3 tests improvements

---

openshift/deploy.sh
openshift/env-template.sh
openshift/helpers.sh

Mixed bag, mostly refactoring. I was hoping to fix the jobs service auth issue, but no luck :/

[openshift] Deploy script improvements

---

integration-tests/features/steps/stack_analysis.py

This is just slightly improvements of all test steps that access versioned stack analysis endpoint.

The stack analysis version is a number, not any string

---

docker-compose.devel.yml
docker-compose.yml

For: https://github.com/fabric8-analytics/fabric8-analytics-jobs/issues/239

Add docker-compose configuration to connect jobs with data-model-importer

---

reproducers/README.md
reproducers/issue1619.py
reproducers/issue1934.py
reproducers/issue2012.py
reproducers/setup.cfg

I feel/hope that a reproducers for issues found in the fabric8-analytics service might be useful for other people as well (and to have a backup as well ;)

Reproducers

---

openshift/deploy.sh
openshift/env-template.sh
openshift/helpers.sh
openshift/secrets-template.yaml

Needed for https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/504
Related to https://github.com/openshiftio/openshift.io/issues/1883

[openshift] Libraries.io API token

---

integration-tests/features/server_api.feature
integration-tests/features/src/schema_validator.py
integration-tests/features/steps/server_api.py

Tests for the /schemas* REST API endpoints:
https://github.com/openshiftio/openshift.io/issues/1786

Implementation for issue 1786

---

integration-tests/features/gremlin.feature
integration-tests/features/src/attribute_checks.py
integration-tests/features/steps/gremlin.py
integration-tests/requirements.in
integration-tests/requirements.txt

Original issue:
https://github.com/openshiftio/openshift.io/issues/2108

Issue 2108: The test that checks packages stored in Gremlin should have better logic for the latest_version property

---

CONTRIBUTING.md
README.md
check-docstyle.sh
run-linter.sh

The content of openshift directory, other scripts, and configuration files has been moved to another directory, but some small changes has to be done in existing repo ;)

Reflect openshift directory move

---

integration-tests/features/server_api.feature
integration-tests/features/steps/server_api.py

https://github.com/openshiftio/openshift.io/issues/1740

Add an integration test for submit-feedback endpoint

---

integration-tests/features/component_search.feature
integration-tests/features/steps/component_analysis.py

change in test for component search

---

dashboard/ci_jobs.ini
dashboard/src/ci_jobs.py
dashboard/src/dashboard.py

Ability to display info about Gemini server on Code quality table and CI jobs table as can be already seen there:

Add gemini to QA dashboard

---

integration-tests/features/gremlin.feature

Fix for 'errors' found by integration tests.

Remove check for leftovers found in graph DB

---

dashboard/ci_jobs.ini

https://github.com/openshiftio/openshift.io/issues/2454

The last step needed to close #2454

---

dashboard/src/dashboard.py
dashboard/src/html_generator.py
dashboard/template/dashboard.css
dashboard/template/repo_details.html

https://github.com/openshiftio/openshift.io/issues/2497
Results:
https://fabric8-analytics.github.io/dashboard/repository_fabric8-analytics-worker.html

Fix for issue 2497

---

integration-tests/features/gremlin.feature
integration-tests/features/steps/gremlin.py

Yet another leftover hidden in the very dark corner...

Fix version checks

---

integration-tests/data/package.json
integration-tests/features/stack_analyses.feature
integration-tests/features/steps/stack_analysis.py

Signed-off-by: Avishkar Gupta <avgupta@redhat.com>

Add integration tests for NPM E2E flow

---

integration-tests/README.md
integration-tests/cico_run_tests.sh
integration-tests/feature_list.txt
integration-tests/features/resilient_infrastructure.feature
integration-tests/features/src/utils.py
integration-tests/features/steps/common.py
integration-tests/features/steps/oc.py
integration-tests/features/steps/server_api.py

@GeetikaBatra I'd need your help. Could you please run the new tests against your dev. instance and check the results? Thank you in advance.

Resilient infra 1

---

dashboard/clone_or_pull_all_repos.sh
dashboard/config.ini
dashboard/src/dashboard.py
dashboard/src/source_files.py

Implementation for issue https://github.com/openshiftio/openshift.io/issues/3730

Issue 3730

---

dashboard/requirements.in
dashboard/requirements.txt
dashboard/src/config.py
dashboard/src/dashboard.py
dashboard/src/html_generator.py
dashboard/src/source_files.py
dashboard/src/unit_tests.py

Implementation for https://github.com/openshiftio/openshift.io/issues/3780

Comprehensible logs for QA dashboard

---

check-bashscripts.sh
check-docstyle.sh
list-todo.sh
measure-cyclomatic-complexity.sh
measure-maintainability-index.sh
run-linter.sh

Problem description: https://github.com/openshiftio/openshift.io/issues/3751

Fix problems found by shellcheck

---

integration-tests/cico_run_tests.sh
integration-tests/cico_setup.sh
integration-tests/features/environment.py
integration-tests/features/license_analysis.feature
integration-tests/features/steps/license_analysis.py

The new tests won't be run on stage ATM because they are not specified in `feature_list.txt`

License analysis e2e tests the stub

---

reproducers/issue4071.py
reproducers/issue4071_wrong_input_missing_ecosystem.json
reproducers/issue4071_wrong_input_missing_package_name.json
reproducers/issue4071_wrong_input_missing_package_name_and_version.json
reproducers/issue4071_wrong_input_missing_package_version.json
reproducers/issue4071_wrong_input_missing_resolved.json

Related issue: https://github.com/openshiftio/openshift.io/issues/4071

Reproducer for issue 4071

---

integration-tests/feature_list.txt
integration-tests/features/gemini.feature

Signed Off by: Geetika Batra<gbatra@redhat.com>

Uncommenting Gemini Feature

---

Dockerfile
check-docstyle.sh
cico_run_pydoc.sh
cico_run_pylint.sh
detect-common-errors.sh
detect-dead-code.sh
measure-cyclomatic-complexity.sh
measure-maintainability-index.sh
run-linter.sh

Fix for issue https://github.com/fabric8-analytics/fabric8-analytics-common/issues/758

Update to Python 3.6

---

e2e_tests_bot/src/ci_jobs.py

Refactored to reduce cyclomatic complexity for function read_build_history()

Refactored to reduce cyclomatic complexity for function read_build_history()

---

dashboard/src/csv_exporter.py

Fix for issue https://github.com/fabric8-analytics/fabric8-analytics-common/issues/894

Refactored function export_code_coverage_into_csv()

---

dashboard/src/code_quality_label.py

Fix for issue https://github.com/fabric8-analytics/fabric8-analytics-common/issues/897

Refactored method Element.count_real_x_y()

---

vscode-visual-tests/features/src/gui.py
vscode-visual-tests/features/steps/ui_checks.py

We need to have the ability to right click into the UI to perform several UI tests (context menu etc.)

Implementation of right click

---

vscode-visual-tests/projects/npm_0_dependencies_0_CVEs/package.json

Implementation for https://github.com/fabric8-analytics/fabric8-analytics-common/issues/905

NPM project with no dependencies and no CVEs

---

dashboard/src/code_quality_label.py

Fix for the issue https://github.com/fabric8-analytics/fabric8-analytics-common/issues/898

Refactored to decrease cyclomatic complexity in method dashboard/src/code_quality_label.py:Element.build()

---

integration-tests/features/environment.py

Fixed issue #938 by refactoring the function retrieve_access_token()

---

job-checker/src/job_checker.py

Fix for https://github.com/fabric8-analytics/fabric8-analytics-common/issues/956

Fix issue #956: refactoring to reduce cyclomatic complexity

---

integration-tests/features/steps/user_tag.py

Better check for response type + actual data

---

integration-tests/feature_list.txt
integration-tests/features/component_analysis.feature
integration-tests/features/steps/component_analysis.py

Component analysis tests for components (package+version) without CVEs.

Component analysis test components without CVE

---

integration-tests/data/array_split.json
integration-tests/data/fastlog_urllib_requests.json
integration-tests/data/junit.xml
integration-tests/data/numpy_1_11_0.json
integration-tests/data/numpy_1_12_0.json
integration-tests/data/numpy_1_16_2.json
integration-tests/data/numpy_1_16_3.json
integration-tests/data/numpy_scipy.json
integration-tests/data/pytest_2_0_0.json
integration-tests/data/pytest_2_0_1.json
integration-tests/data/pytest_3_2_2.json
integration-tests/data/requests_2_20_0.json
integration-tests/data/requests_2_20_1.json
integration-tests/data/requests_2_21_0.json
integration-tests/data/requirements2.txt
integration-tests/data/requirements_click_6_7.json
integration-tests/data/requirements_click_7_0.json
integration-tests/data/scipy_1_1_0.json
integration-tests/data/scipy_1_2_0.json
integration-tests/data/scipy_1_2_1.json
integration-tests/data/vertx_3_4_1.xml
integration-tests/data/vertx_3_4_2.xml
integration-tests/feature_list.txt
integration-tests/features/stack_analyses_pypi_ecosystem_pylist.feature
integration-tests/features/steps/stack_analysis.py

Checks whether the basic `pylist.json` files are handled properly by the server.

Pylist tests based on `pylist.json`

---

vscode-visual-tests/projects/maven_0_dependencies_0_CVEs/pom.xml
vscode-visual-tests/projects/maven_1_dependency_0_CVEs/pom.xml
vscode-visual-tests/projects/maven_1_dependency_1_CVE/pom.xml
vscode-visual-tests/projects/maven_5_dependencies_0_CVEs/pom.xml
vscode-visual-tests/projects/maven_5_dependencies_1_CVE/pom.xml
vscode-visual-tests/projects/maven_5_dependencies_2_CVEs/pom.xml
vscode-visual-tests/projects/maven_5_dependencies_3_CVEs/pom.xml
vscode-visual-tests/projects/maven_5_dependencies_4_CVEs/pom.xml
vscode-visual-tests/projects/maven_5_dependencies_5_CVEs/pom.xml

Implementations for issues#
https://github.com/fabric8-analytics/fabric8-analytics-common/issues/891
https://github.com/fabric8-analytics/fabric8-analytics-common/issues/930
etc.

Maven projects for VSCode tests

---

a2t/data/maven_0_dependencies_0_CVEs.xml
a2t/data/maven_1_dependency_0_CVEs.xml
a2t/data/maven_1_dependency_1_CVE.xml
a2t/data/maven_5_dependencies_0_CVEs.xml
a2t/data/maven_5_dependencies_1_CVE.xml
a2t/data/maven_5_dependencies_2_CVEs.xml
a2t/data/maven_5_dependencies_3_CVEs.xml
a2t/data/maven_5_dependencies_4_CVEs.xml
a2t/data/maven_5_dependencies_5_CVEs.xml
a2t/data/npm_0_dependencies_0_CVEs.json
a2t/data/npm_1_dependency_0_CVEs.json
a2t/data/npm_1_dependency_1_CVE.json
a2t/data/npm_5_dependencies_0_CVEs.json
a2t/data/npm_5_dependencies_1_CVE.json
a2t/data/npm_5_dependencies_2_CVEs.json
a2t/data/npm_5_dependencies_3_CVEs.json
a2t/data/npm_5_dependencies_4_CVEs.json
a2t/data/npm_5_dependencies_5_CVEs.json

For getting better (=closer to real usage) results, we need some stacks with CVEs to be used in load tests

Stacks with CVEs and without CVEs for load tests

---

integration-tests/features/stack_analyses_pypi_ecosystem.feature

update license count

---

integration-tests/features/stack_analyses_maven_ecosystem.feature
integration-tests/features/stack_analyses_npm_ecosystem.feature
integration-tests/features/stack_analyses_pypi_ecosystem.feature
integration-tests/features/stack_analyses_pypi_ecosystem_pylist.feature
integration-tests/runtest.sh

Let's not run all data-sanity-related tests for PRs

Data sanity tests

---

integration-tests/features/environment.py
integration-tests/features/src/stack_analysis_common.py
integration-tests/features/steps/stack_analysis.py

Refactor for stack analysis tests

---

job-checker/src/job_checker.py

To be able to check if all CI jobs are configured properly, we need to check the job status and job badge in job checker.

Implementation of issue #1017

---

integration-tests/features/src/stack_analysis_common.py
integration-tests/features/steps/stack_analysis.py

Fix for https://github.com/fabric8-analytics/fabric8-analytics-common/issues/1030

Refactor get json data function

---

a2t/src/setup.py

Refactored function setup.py to reduce cyclomatic complexity

---

db-integrity-tests/src/checker.py

Fix for the issue https://github.com/fabric8-analytics/fabric8-analytics-common/issues/971

Refactored function Checker.check_cve_value()

---

perf-tests/src/jobsapi.py

Fix for the issue https://github.com/fabric8-analytics/fabric8-analytics-common/issues/862

Method to dump JSON responses

---

dashboard/src/code_quality_label.py

Fixed the computation of maintainability index, so the max percentage might reach 100%.

Fix the issue #1059

---

perf-tests/src/perf-tests.py

Fix for the issue https://github.com/fabric8-analytics/fabric8-analytics-common/issues/864

Reractor function to export results

---

integration-tests/features/src/stack_analysis_common.py

Refactored function check_frequency_count()

---

integration-tests/features/steps/gremlin.py

Refactored function package_data_timestamp_comparison_with_remembered_time

---

integration-tests/features/steps/license_analysis.py

Refactored function check_license_analysis_conflicts_for_package_version

---

tools/generate_pypi_list.py

Implementation of https://github.com/fabric8-analytics/fabric8-analytics-common/issues/1081

Script to generate list of PyPi packages

---

integration-tests/features/steps/server_api.py

https://github.com/fabric8-analytics/fabric8-analytics-common/issues/967

Fixed issue #967 - refactored function post_input_to_user_feedback

---

dashboard/src/html_generator.py

https://github.com/fabric8-analytics/fabric8-analytics-common/issues/896

Fix issue #896

---

integration-tests/data/npm_100_direct_1039_tr.json
integration-tests/data/npm_10_direct.json
integration-tests/data/npm_150_direct_1170_tr.json
integration-tests/data/npm_1_direct.json
integration-tests/data/npm_50_direct_799_tr.json
integration-tests/feature_list.txt
integration-tests/features/stack_analyses_smoke_tests_npm_ecosystem.feature
integration-tests/features/stack_analysis_npm_direct_and_transitive.feature
integration-tests/features/steps/stack_analysis.py

Issue https://github.com/fabric8-analytics/fabric8-analytics-common/issues/1024

Stack analysis for selected npm ecosystems

---

tools/generate_maven_list.py

Create script to generate a list of X most used Maven packages (E/P/V)
That script will be used to generate e2e tests for the component analysis.

Fix issue #1082: Create script to generate a list of X most used Maven packages (E/P/V)

---

SOP.md

The stub for SOP document

---

integration-tests/CI_README.adoc
integration-tests/README.adoc
integration-tests/env.sh
integration-tests/refresh_token_scripts/get_refresh_token_part.py
integration-tests/refresh_token_scripts/urldecode.sh
integration-tests/runtest.sh

Updated Integration Test Readme to match the latest followed procedures. 
Added Environment variables to run tests at the local environment.
Separate ReadMe for local and CI environment.
Documentation Issue
- [x ] New feature (non-breaking change which adds functionality)

Readme updated | Environment variables added

---

integration-tests/feature_list.txt
integration-tests/features/gemini.feature
integration-tests/features/src/attribute_checks.py
integration-tests/features/steps/gemini.py

Reenable the Gemini tests and check the stack analysis report more extensively.
Fixes #1096

Stacks report gemini tests

---

integration-tests/env.sh
integration-tests/features/steps/stack_analysis.py

Added Support for Ecosystem and Origin in E2E Stack Analyses
https://github.com/fabric8-analytics/fabric8-analytics-common/issues/1038
https://github.com/fabric8-analytics/fabric8-analytics-common/issues/1037

Adding support for Origin and Ecosystem in Stack Analyses

---

SOP.md

New case added to SOP

---

SOP.md

SOP issue: cico node get failed

CI failure: cico node get failed

---

dashboard/src/perf_tests.py

Fixed issue #1135

---

dashboard/ci_jobs.ini
dashboard/config.ini

Add data ingestion service to QA Dashboard

---

dashboard/src/dashboard.py

Please look at #1138
Fixes #1138

Display number of processed repositories in the dashboard data pipeline

---

README.adoc

Added link to SOP document

---

integration-tests/README.adoc

Link to SOP document in integration tests README

Link to SOP document in integration tests README

---

README.adoc

Fixed links in the main README.adoc file

Fixed links in README.adoc

---

dashboard/ci_jobs.ini
dashboard/clone_or_pull_all_repos.sh
dashboard/config.ini

Add f8a emr deployment into dashboard
Fixes #724

Add f8a emr deployment into dashboard

---

integration-tests/README.adoc
integration-tests/features/gemini.feature
integration-tests/features/steps/gemini.py

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #1144

Checks for daily stack reports

---

integration-tests/README.adoc

Update for the documentation for integration tests.

Integration tests documentation update

---

integration-tests/generate_scenarios.sh

Script to generate list of scenarios

Script to generate list of scenarios

---

integration-tests/README.adoc

Links to list of scenarios

---

dashboard/about_qa_dashboard_code_coverage_report.adoc

Fixed links and updated documentation.

Fixed links, updated documentation

---

integration-tests/features/src/attribute_checks.py

Fixed time duration check

---

qa/list_all_nocov.sh

Script to list all pragmas in source codes

Script to list all pragmas in source codes

---

dashboard/src/dashboard.py
dashboard/src/dc_ce_history.py

Minor QA dashboard refactoring

Minor dashboard refactoring

---

integration-tests/feature_list.txt

Some tests not used in production needs to be disabled

disable tests for endpoints not used in production

---

integration-tests/features/stack_analyses.feature

Pausing Dynamic Manifests E2E. E2E Failing Because of this scnerio. Pausing this for Debugging and unblocking other PR's.

pausing e2e

---

README.adoc

Retriggering CI, Last CI failing because of unexpected reasons.
https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/2411/console
https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/2411/console

Trigger CI

---

README.adoc

Reverts fabric8-analytics/fabric8-analytics-common#1171
CI Re Trigger: https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/2412/console

Revert "Trigger CI"

---

dashboard/ci_jobs.ini
dashboard/config.ini
dashboard/dashboard.sh
dashboard/src/source_files.py
integration-tests/features/stack_analyses.feature
integration-tests/features/stack_analyses_npm_ecosystem.feature
integration-tests/features/steps/gremlin.py
integration-tests/features/steps/jobs_api.py
integration-tests/features/steps/license_analysis.py
integration-tests/features/steps/stack_analysis.py
vscode-visual-tests/features/steps/common.py

added the following repository to the QA Dashboard:
https://github.com/fabric8-analytics/fabric8-analytics-lsp-server
#1062
- [*] Bug fix (non-breaking change which fixes an issue)
- [ *] New feature (non-breaking change which adds functionality)

added lsp-server to dashboard

---

integration-tests/features/component_analysis.feature
integration-tests/features/src/utils.py

updated version of jquery in component analysis feature 
version 3.4.0 to 3.5.0
- [X ] Bug fix (non-breaking change which fixes an issue)

updated version of jquery in component analysis feature

---

integration-tests/features/component_analysis.feature
integration-tests/features/stack_analyses.feature
integration-tests/features/stack_analyses_maven_ecosystem.feature
integration-tests/features/stack_analyses_npm_ecosystem.feature
integration-tests/features/stack_analyses_pypi_ecosystem.feature
integration-tests/features/stack_analyses_pypi_ecosystem_pylist.feature
integration-tests/features/stack_analyses_smoke_tests_npm_ecosystem.feature
integration-tests/features/stack_analyses_smoke_tests_pypi_ecosystem.feature
integration-tests/features/stack_analyses_unknown_dependencies.feature
integration-tests/features/stack_analyses_v2.feature
integration-tests/features/stack_analyses_v2_minimal.feature
integration-tests/features/stack_analysis_maven_direct_and_transitive.feature
integration-tests/features/stack_analysis_npm_direct_and_transitive.feature
integration-tests/features/stack_analysis_pypi_direct_and_transitive.feature
integration-tests/features/steps/stack_analysis.py
integration-tests/features/steps/three_scale_preview.py
integration-tests/features/three_scale_component_analyses.feature
integration-tests/features/three_scale_stack_analyses.feature

Skipped irrelevant tests, fixed the dependency errors and modified stack analysis tests to use 3scale auth
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)

fixes and made stack analysis tests use 3scale auth

---

integration-tests/features/component_analysis.feature

removed lodash and added a different dependency , component analysis e2e fix
- [X ] Bug fix (non-breaking change which fixes an issue)

Dependencies fix e2e

---

integration-tests/cico_run_tests.sh
integration-tests/cico_setup.sh
integration-tests/feature_list.txt
integration-tests/features/component_analysis_v2.feature
integration-tests/features/component_analysis_v2_smoke_tests.feature
integration-tests/features/environment.py
integration-tests/features/steps/component_analysis_v2.py
integration-tests/scenarios/component_analysis_v2.md
integration-tests/scenarios/component_analysis_v2_smoke_tests.md
integration-tests/scenarios/components.md
integration-tests/scenarios/stack_analyses.md
integration-tests/scenarios/stack_analysis_npm_direct_and_transitive.md

LSP API V2 Tests and some dependency fixes

component analysis v2 tests and fixes

---

integration-tests/features/component_analysis_v2.feature

429 fixes 
- [ X] Bug fix (non-breaking change which fixes an issue)

fixed 429 errors

---

integration-tests/features/src/authorization_tokens.py
integration-tests/features/stack_analyses_v2.feature
integration-tests/features/steps/stack_analyses_v2.py

Avoid transitive dependency scan for stack analyses v2
https://issues.redhat.com/browse/APPAI-1357

[APPAI-1357] Avoid transitive dependency scan for stack analyses v2

---

integration-tests/features/steps/stack_analyses_v2.py

Modified e2e test cases to handle changes made due to below jira issues:
https://issues.redhat.com/browse/APPAI-1325
https://issues.redhat.com/browse/APPAI-1326
https://issues.redhat.com/browse/APPAI-1347

[APPAI-1325] [APPAI-1326] [APPAI-1347] SA Handling error codes for 400 and 405

---

integration-tests/data/vertx_dependencies.txt
integration-tests/feature_list.txt
integration-tests/features/stack_analyses_v2_valid_dynamic.feature
integration-tests/features/steps/stack_analyses_v2.py
integration-tests/scenarios/component_analysis_smoke_tests_100_npm_components.md
integration-tests/scenarios/component_analysis_v2.md
integration-tests/scenarios/stack_analyses_v2_valid_dynamic.md

Tests included in this are 
Type:

Dynamic manifests and data validation tests

---

integration-tests/features/server_api.feature
integration-tests/features/steps/server_api.py

Fixed the test to use the three scale api .

BUG FIX : production e2e job fixes

---

integration-tests/features/component_analysis_v2.feature
integration-tests/features/steps/component_analysis_v2.py

Tests for the new meta data changes about package vulnerablity in component analysis api described here : https://issues.redhat.com/browse/APPAI-1411

Updated Tests - [Component Analyses] Add more meta data about package vulnerability - APPAI-1411

---

integration-tests/features/stack_analyses_v2_valid_dynamic.feature

Commented out pylist.json tests

commenting out pylist.json tests

---

integration-tests/features/stack_analyses_v2.feature
integration-tests/features/stack_analyses_v2_smoke.feature

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Removing tests cases related to Kronos

---

cico_run_pylint.sh
integration-tests/features/steps/component_analysis_v2_batchcall.py
integration-tests/features/steps/stack_analyses_v2.py
integration-tests/features/user_management.feature
qa/measure-maintainability-index.sh

This Specific PR deals with adding of new tests that will extend for Registered Users e2e flow for stack analysis and component analysis.

Chore: Extend User Management Tests Support for SA and CA [APPAI - 1486]

---

integration-tests/features/user_management.feature

simple e2e fix : it was throwing 408 for pylist test

fix : e2e tests

---

integration-tests/features/stack_analyses_v2.feature
integration-tests/features/stack_analyses_v2_valid_dynamic.feature

testing if e2e is stable with wait time increased

added wait time inorder to make e2e stable

---

integration-tests/features/user_management.feature

user management fix

---

integration-tests/data/batch_call/both_module_package_vuln.json
integration-tests/data/batch_call/module_package_not_vuln.json
integration-tests/data/batch_call/module_vuln_package_not.json
integration-tests/data/batch_call/package_vuln_module_not.json
integration-tests/data/batch_call/pseudo_version.json
integration-tests/data/batch_call/test_golang.json
integration-tests/data/batch_call/test_golang_1.json
integration-tests/data/batch_call/test_golang_2.json
integration-tests/data/batch_call/test_golang_3.json
integration-tests/feature_list.txt
integration-tests/features/component_analysis_golang.feature

Contains scenarios to test component analysis API for Golang ecosystem

chore : Component Analysis E2E tests for Golang Ecosystem

---

.github/workflows/hourly.yml
hourly-tests/data/pylist.json
hourly-tests/hourly-test.py
qa/directories.txt

Changes contain code that provides hourly tests for CA and SA using Github actions

Chore : Add Hourly tests [APPAI-1661]

---

integration-tests/features/component_analysis_golang.feature
integration-tests/features/component_analysis_v2_batchcall.feature
integration-tests/features/steps/component_analysis_v2_batchcall.py

fixed test case for unknown package key error "name" 
Fixes # (issue):
https://issues.redhat.com/browse/APPAI-1675

Component Analysis Fixes

---

.github/workflows/ci-build.yml
.github/workflows/ci-run-e2e.yml
.github/workflows/slash-command.yml
README.adoc
qa/measure-cyclomatic-complexity.sh
qa/measure-maintainability-index.sh

Enables Use of github actions to run integration tests.

chore: Migrate CI to github actions

---

integration-tests/features/stack_analyses_v2_valid_dynamic.feature

E2E version Fix

---

integration-tests/features/component_analysis_v2.feature
integration-tests/features/steps/s3_component_analysis.py

Disabling unknown component test to over come CD error [ will enable it after CD passes ]

Update Response for Unknown package in CA v2 tests

---

integration-tests/features/stack_analyses_v2_valid_dynamic.feature

fix: e2e package ingestion - feature data validation maven 

---

integration-tests/features/stack_analyses_v2_valid_dynamic.feature

fix : e2e ingestion fix

---

README.adoc

just fixed broken status badge link

chore: Update Build status

---

.github/workflows/conventional-commit-msg.yml

signed off by msawood@redhat.com

core: Support Conventional commits

---

integration-tests/build_deploy.sh

ci: Build push job fix

---

integration-tests/openshift/f8a-e2e-tests.yaml

add a unique job id for each job

ci: associate a job id with the job

---

integration-tests/features/stack_analyses_v2_valid_dynamic.feature

fix: e2e ingestion

---

integration-tests/features/stack_analyses_v2_valid_dynamic.feature

This Pull Request updates the test cases based on latest package ingestion

fix: e2e latest package ingestion

---

integration-tests/data/batch_call/test_pypi.json
integration-tests/features/component_analysis_v2.feature

fix: e2e recommendation package ingestion

---

integration-tests/features/stack_analyses_v2_valid_dynamic.feature

Component io.vertx:vertx-core have changed to 4.1.0.CR2 from 4.1.0.CR1

fix: e2e fix

---

integration-tests/features/stack_analyses_v2_valid_dynamic.feature

Component io.vertx:vertx-core have changed to 4.1.0.CR2 from 4.1.0

fix: e2e ingestion fix

---

integration-tests/features/stack_analyses_v2_valid_dynamic.feature

e2e fixes signed off by msawood@redhat.com

fix: e2e latest pacakges

---

integration-tests/feature_list.txt
integration-tests/features/steps/vulnerablity-analysis.py
integration-tests/features/vulnerability_analysis.feature

Added Tests for the new API which will be used by CLAIR / QUAY

chore: Add tests for Vulnerability analysis API

---

integration-tests/features/stack_analyses_v2_valid_dynamic.feature

fix: latest package ingestion

---

integration-tests/e2e.sh

Reverts fabric8-analytics/fabric8-analytics-common#1277

revert: "fix: Disable e2e for postgres upgrade"

---

integration-tests/data/package.json
integration-tests/features/component_analysis_v2.feature
integration-tests/features/component_analysis_v2_batchcall.feature
integration-tests/features/user_management.feature

This PR fixes the e2e on stage .

fix: e2e failure caused by upgrade activity and ingestion 
